### ISSUE TITLE
np selective seq in 3pages of ppt, chinese

### ISSUE THREAD

**Issue by sunhaocuhk** [cuhk-haosun/doc-nanopore#16]

**Comment by Milokita** [comment]
已上传 https://github.com/cuhk-haosun/doc-nanopore/blob/7fa21f0e6f8044e1191f6f2fefe07f2d963cc2c4/presentation/nanopore%E9%80%89%E6%8B%A9%E6%B5%8B%E5%BA%8F.pptx
